### ISSUE TITLE
parent_model() fails with django 1.8

### ISSUE THREAD

**Issue by orlovegor** [burke-software/django-report-utils#11]
AttributeError: 'ManyToOneRel' object has no attribute 'parent_model'

![2015-04-03 18-32-51 exception happed in processing request report_builder api report 22 generate partner sentry](https://cloud.githubusercontent.com/assets/4242339/6984284/dd36786a-da2f-11e4-9cd5-d8b05f98fe06.png)

**Comment by bufke** [comment]
Thanks for reporting!

**Comment by orlovegor** [comment]
Thanks!
